"""convert file purpose relationship to many to many

Revision ID: 976392921ccf
Revises: 32f9ee461e64
Create Date: 2025-06-26 10:28:51.217144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976392921ccf'
down_revision: Union[str, Sequence[str], None] = '32f9ee461e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the new junction table
    op.create_table('purpose_file_attachment',
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('file_attachment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_attachment_id'], ['file_attachment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('purpose_id', 'file_attachment_id')
    )
    
    # Migrate existing data from file_attachment.purpose_id to junction table
    op.execute("""
        INSERT INTO purpose_file_attachment (purpose_id, file_attachment_id)
        SELECT purpose_id, id
        FROM file_attachment
        WHERE purpose_id IS NOT NULL
    """)
    
    # Remove the old foreign key and column
    op.drop_index(op.f('ix_file_attachment_purpose_id'), table_name='file_attachment')
    op.drop_constraint(op.f('file_attachment_purpose_id_fkey'), 'file_attachment', type_='foreignkey')
    op.drop_column('file_attachment', 'purpose_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_attachment', sa.Column('purpose_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('file_attachment_purpose_id_fkey'), 'file_attachment', 'purpose', ['purpose_id'], ['id'])
    op.create_index(op.f('ix_file_attachment_purpose_id'), 'file_attachment', ['purpose_id'], unique=False)
    op.drop_table('purpose_file_attachment')
    # ### end Alembic commands ###
