"""init

Revision ID: cb0054726125
Revises: 
Create Date: 2025-07-07 12:55:29.418021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0054726125'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_file_attachment_id'), 'file_attachment', ['id'], unique=False)
    op.create_table('hierarchy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('UNIT', 'CENTER', 'ANAF', 'MADOR', 'TEAM', name='hierarchytypeenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['hierarchy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hierarchy_id'), 'hierarchy', ['id'], unique=False)
    op.create_index(op.f('ix_hierarchy_path'), 'hierarchy', ['path'], unique=False)
    op.create_table('predefined_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flow_name')
    )
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_type_id'), 'service_type', ['id'], unique=False)
    op.create_index(op.f('ix_service_type_name'), 'service_type', ['name'], unique=True)
    op.create_table('stage_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('file_icon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_icon_id'], ['file_attachment.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_name'), 'supplier', ['name'], unique=True)
    op.create_table('predefined_flow_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predefined_flow_id', sa.Integer(), nullable=False),
    sa.Column('stage_type_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['predefined_flow_id'], ['predefined_flow.id'], ),
    sa.ForeignKeyConstraint(['stage_type_id'], ['stage_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purpose',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'SIGNED', 'PARTIALLY_SUPPLIED', name='statusenum'), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('hierarchy_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['hierarchy.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purpose_description'), 'purpose', ['description'], unique=False)
    op.create_index(op.f('ix_purpose_hierarchy_id'), 'purpose', ['hierarchy_id'], unique=False)
    op.create_index(op.f('ix_purpose_id'), 'purpose', ['id'], unique=False)
    op.create_index(op.f('ix_purpose_service_type_id'), 'purpose', ['service_type_id'], unique=False)
    op.create_index(op.f('ix_purpose_status'), 'purpose', ['status'], unique=False)
    op.create_index(op.f('ix_purpose_supplier_id'), 'purpose', ['supplier_id'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'service_type_id', name='uq_service_name_service_type')
    )
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_index(op.f('ix_service_name'), 'service', ['name'], unique=False)
    op.create_index(op.f('ix_service_service_type_id'), 'service', ['service_type_id'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('predefined_flow_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['predefined_flow_id'], ['predefined_flow.id'], ),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purpose_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purpose_id', 'service_id', name='uq_purpose_service')
    )
    op.create_index(op.f('ix_purpose_content_id'), 'purpose_content', ['id'], unique=False)
    op.create_index(op.f('ix_purpose_content_purpose_id'), 'purpose_content', ['purpose_id'], unique=False)
    op.create_index(op.f('ix_purpose_content_service_id'), 'purpose_content', ['service_id'], unique=False)
    op.create_table('purpose_file_attachment',
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('file_attachment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_attachment_id'], ['file_attachment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('purpose_id', 'file_attachment_id')
    )
    op.create_table('cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('SUPPORT_USD', 'AVAILABLE_USD', 'ILS', name='currencyenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_id'), 'cost', ['id'], unique=False)
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_type_id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['stage_type_id'], ['stage_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage')
    op.drop_index(op.f('ix_cost_id'), table_name='cost')
    op.drop_table('cost')
    op.drop_table('purpose_file_attachment')
    op.drop_index(op.f('ix_purpose_content_service_id'), table_name='purpose_content')
    op.drop_index(op.f('ix_purpose_content_purpose_id'), table_name='purpose_content')
    op.drop_index(op.f('ix_purpose_content_id'), table_name='purpose_content')
    op.drop_table('purpose_content')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_service_service_type_id'), table_name='service')
    op.drop_index(op.f('ix_service_name'), table_name='service')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_purpose_supplier_id'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_status'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_service_type_id'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_id'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_hierarchy_id'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_description'), table_name='purpose')
    op.drop_table('purpose')
    op.drop_table('predefined_flow_stage')
    op.drop_index(op.f('ix_supplier_name'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_table('stage_type')
    op.drop_index(op.f('ix_service_type_name'), table_name='service_type')
    op.drop_index(op.f('ix_service_type_id'), table_name='service_type')
    op.drop_table('service_type')
    op.drop_table('predefined_flow')
    op.drop_index(op.f('ix_hierarchy_path'), table_name='hierarchy')
    op.drop_index(op.f('ix_hierarchy_id'), table_name='hierarchy')
    op.drop_table('hierarchy')
    op.drop_index(op.f('ix_file_attachment_id'), table_name='file_attachment')
    op.drop_table('file_attachment')
    # ### end Alembic commands ###
