"""service_type relationship

Revision ID: cfbb285be047
Revises: d1f30f0d9d8b
Create Date: 2025-06-21 16:53:23.871385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbb285be047'
down_revision: Union[str, Sequence[str], None] = 'd1f30f0d9d8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purpose', sa.Column('service_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purpose', 'service_type', ['service_type_id'], ['id'])
    op.drop_column('purpose', 'service_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purpose', sa.Column('service_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purpose', type_='foreignkey')
    op.drop_column('purpose', 'service_type_id')
    # ### end Alembic commands ###
