"""purpose_service_relation

Revision ID: 6eee6789fa73
Revises: 496f857515f0
Create Date: 2025-06-22 19:34:41.140154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eee6789fa73'
down_revision: Union[str, Sequence[str], None] = '496f857515f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purpose_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purpose_id', 'service_id', name='uq_purpose_service')
    )
    op.create_index(op.f('ix_purpose_content_id'), 'purpose_content', ['id'], unique=False)
    op.create_index(op.f('ix_purpose_content_purpose_id'), 'purpose_content', ['purpose_id'], unique=False)
    op.create_index(op.f('ix_purpose_content_service_id'), 'purpose_content', ['service_id'], unique=False)
    op.drop_index(op.f('ix_purpose_content'), table_name='purpose')
    op.drop_column('purpose', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purpose', sa.Column('content', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_purpose_content'), 'purpose', ['content'], unique=False)
    op.drop_index(op.f('ix_purpose_content_service_id'), table_name='purpose_content')
    op.drop_index(op.f('ix_purpose_content_purpose_id'), table_name='purpose_content')
    op.drop_index(op.f('ix_purpose_content_id'), table_name='purpose_content')
    op.drop_table('purpose_content')
    # ### end Alembic commands ###
