"""Add responsible_authority to stage_type

Revision ID: b60cbb1cb192
Revises: 2c70acc4859b
Create Date: 2025-07-27 10:51:10.622806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60cbb1cb192'
down_revision: Union[str, Sequence[str], None] = '2c70acc4859b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_type', sa.Column('responsible_authority', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_type', 'responsible_authority')
    # ### end Alembic commands ###
