"""Add generic indexes and responsible_authority field for better query performance

Revision ID: aaf72e5b9fcd
Revises: 2c70acc4859b
Create Date: 2025-07-28 11:35:16.468743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf72e5b9fcd'
down_revision: Union[str, Sequence[str], None] = '2c70acc4859b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_purchase_purpose_id'), 'purchase', ['purpose_id'], unique=False)
    op.create_index(op.f('ix_stage_purchase_id'), 'stage', ['purchase_id'], unique=False)
    op.add_column('stage_type', sa.Column('responsible_authority', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_stage_type_responsible_authority'), 'stage_type', ['responsible_authority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_type_responsible_authority'), table_name='stage_type')
    op.drop_column('stage_type', 'responsible_authority')
    op.drop_index(op.f('ix_stage_purchase_id'), table_name='stage')
    op.drop_index(op.f('ix_purchase_purpose_id'), table_name='purchase')
    # ### end Alembic commands ###
