"""add predefined_flow_id to purchase and drop emf table

Revision ID: dfb140a1cb64
Revises: 85221d67b5af
Create Date: 2025-07-06 16:24:38.248117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb140a1cb64'
down_revision: Union[str, Sequence[str], None] = '85221d67b5af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emf_emf_id'), table_name='emf')
    op.drop_index(op.f('ix_emf_id'), table_name='emf')
    op.drop_table('emf')
    op.add_column('cost', sa.Column('purchase_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('cost_emf_id_fkey'), 'cost', type_='foreignkey')
    op.create_foreign_key(None, 'cost', 'purchase', ['purchase_id'], ['id'])
    op.drop_column('cost', 'emf_id')
    op.add_column('purchase', sa.Column('predefined_flow_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase', 'predefined_flow', ['predefined_flow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_column('purchase', 'predefined_flow_id')
    op.add_column('cost', sa.Column('emf_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cost', type_='foreignkey')
    op.create_foreign_key(op.f('cost_emf_id_fkey'), 'cost', 'emf', ['emf_id'], ['id'])
    op.drop_column('cost', 'purchase_id')
    op.create_table('emf',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('emf_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('purpose_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('order_creation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('demand_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('demand_creation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('bikushit_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bikushit_creation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], name=op.f('emf_purpose_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('emf_pkey'))
    )
    op.create_index(op.f('ix_emf_id'), 'emf', ['id'], unique=False)
    op.create_index(op.f('ix_emf_emf_id'), 'emf', ['emf_id'], unique=False)
    # ### end Alembic commands ###
