"""supplier relationship

Revision ID: d1f30f0d9d8b
Revises: defbdc927e9c
Create Date: 2025-06-21 16:40:52.145393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f30f0d9d8b'
down_revision: Union[str, Sequence[str], None] = 'defbdc927e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purpose', sa.Column('supplier_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purpose', 'supplier', ['supplier_id'], ['id'])
    op.drop_column('purpose', 'supplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purpose', sa.Column('supplier', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purpose', type_='foreignkey')
    op.drop_column('purpose', 'supplier_id')
    # ### end Alembic commands ###
