"""add budget source table and purchase foreign key

Revision ID: ce66c21b6a7e
Revises: 5dd5b3c55309
Create Date: 2025-09-07 14:38:04.394653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce66c21b6a7e'
down_revision: Union[str, Sequence[str], None] = '5dd5b3c55309'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_source_id'), 'budget_source', ['id'], unique=False)
    op.create_index(op.f('ix_budget_source_name'), 'budget_source', ['name'], unique=True)
    op.add_column('purchase', sa.Column('budget_source_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_budget_source_id'), 'purchase', ['budget_source_id'], unique=False)
    op.create_foreign_key(None, 'purchase', 'budget_source', ['budget_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_budget_source_id'), table_name='purchase')
    op.drop_column('purchase', 'budget_source_id')
    op.drop_index(op.f('ix_budget_source_name'), table_name='budget_source')
    op.drop_index(op.f('ix_budget_source_id'), table_name='budget_source')
    op.drop_table('budget_source')
    # ### end Alembic commands ###
