"""init

Revision ID: 297142562641
Revises: 
Create Date: 2025-06-21 19:06:47.827405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297142562641'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hierarchy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('UNIT', 'CENTER', 'ANAF', 'MADOR', 'TEAM', name='hierarchytypeenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['hierarchy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hierarchy_id'), 'hierarchy', ['id'], unique=False)
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_type_id'), 'service_type', ['id'], unique=False)
    op.create_index(op.f('ix_service_type_name'), 'service_type', ['name'], unique=True)
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_name'), 'supplier', ['name'], unique=True)
    op.create_table('purpose',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('content', sa.String(length=2000), nullable=True),
    sa.Column('creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='statusenum'), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('last_modified', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_delivery', sa.Date(), nullable=True),
    sa.Column('hierarchy_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['hierarchy.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purpose_id'), 'purpose', ['id'], unique=False)
    op.create_table('emf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emf_id', sa.String(length=255), nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('order_creation_date', sa.Date(), nullable=True),
    sa.Column('demand_id', sa.String(length=255), nullable=True),
    sa.Column('demand_creation_date', sa.Date(), nullable=True),
    sa.Column('bikushit_id', sa.String(length=255), nullable=True),
    sa.Column('bikushit_creation_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['purpose_id'], ['purpose.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emf_emf_id'), 'emf', ['emf_id'], unique=False)
    op.create_index(op.f('ix_emf_id'), 'emf', ['id'], unique=False)
    op.create_table('cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emf_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('SUPPORT_USD', 'AVAILABLE_USD', 'ILS', name='currencyenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['emf_id'], ['emf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_id'), 'cost', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_id'), table_name='cost')
    op.drop_table('cost')
    op.drop_index(op.f('ix_emf_id'), table_name='emf')
    op.drop_index(op.f('ix_emf_emf_id'), table_name='emf')
    op.drop_table('emf')
    op.drop_index(op.f('ix_purpose_id'), table_name='purpose')
    op.drop_table('purpose')
    op.drop_index(op.f('ix_supplier_name'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_service_type_name'), table_name='service_type')
    op.drop_index(op.f('ix_service_type_id'), table_name='service_type')
    op.drop_table('service_type')
    op.drop_index(op.f('ix_hierarchy_id'), table_name='hierarchy')
    op.drop_table('hierarchy')
    # ### end Alembic commands ###
