"""Add performance indexes for pending authority feature

Revision ID: df66c936827a
Revises: 2c70acc4859b
Create Date: 2025-07-28 10:07:08.108932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df66c936827a'
down_revision: Union[str, Sequence[str], None] = '2c70acc4859b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_purchase_purpose', 'purchase', ['purpose_id'], unique=False)
    op.create_index('idx_stage_incomplete_priority', 'stage', ['purchase_id', 'completion_date', 'priority', 'stage_type_id'], unique=False, postgresql_where=sa.text('completion_date IS NULL'))
    op.add_column('stage_type', sa.Column('responsible_authority', sa.String(length=255), nullable=True))
    op.create_index('idx_stage_type_authority', 'stage_type', ['id', 'responsible_authority'], unique=False, postgresql_where=sa.text('responsible_authority IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stage_type_authority', table_name='stage_type', postgresql_where=sa.text('responsible_authority IS NOT NULL'))
    op.drop_column('stage_type', 'responsible_authority')
    op.drop_index('idx_stage_incomplete_priority', table_name='stage', postgresql_where=sa.text('completion_date IS NULL'))
    op.drop_index('idx_purchase_purpose', table_name='purchase')
    # ### end Alembic commands ###
