"""Add ResponsibleAuthority model and relationship

Revision ID: be67b626ac24
Revises: 2c70acc4859b
Create Date: 2025-07-28 15:05:02.972342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be67b626ac24'
down_revision: Union[str, Sequence[str], None] = '2c70acc4859b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible_authority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_responsible_authority_name'), 'responsible_authority', ['name'], unique=True)
    op.create_index(op.f('ix_purchase_purpose_id'), 'purchase', ['purpose_id'], unique=False)
    op.create_index(op.f('ix_stage_purchase_id'), 'stage', ['purchase_id'], unique=False)
    op.add_column('stage_type', sa.Column('responsible_authority_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stage_type_responsible_authority_id'), 'stage_type', ['responsible_authority_id'], unique=False)
    op.create_foreign_key(None, 'stage_type', 'responsible_authority', ['responsible_authority_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage_type', type_='foreignkey')
    op.drop_index(op.f('ix_stage_type_responsible_authority_id'), table_name='stage_type')
    op.drop_column('stage_type', 'responsible_authority_id')
    op.drop_index(op.f('ix_stage_purchase_id'), table_name='stage')
    op.drop_index(op.f('ix_purchase_purpose_id'), table_name='purchase')
    op.drop_index(op.f('ix_responsible_authority_name'), table_name='responsible_authority')
    op.drop_table('responsible_authority')
    # ### end Alembic commands ###
