"""add_indexes_for_performance

Revision ID: 4edbe6d330ef
Revises: 66c7bbe2cbe5
Create Date: 2025-06-22 14:17:36.488049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4edbe6d330ef'
down_revision: Union[str, Sequence[str], None] = '66c7bbe2cbe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_hierarchy_path'), 'hierarchy', ['path'], unique=False)
    op.create_index(op.f('ix_purpose_content'), 'purpose', ['content'], unique=False)
    op.create_index(op.f('ix_purpose_description'), 'purpose', ['description'], unique=False)
    op.create_index(op.f('ix_purpose_hierarchy_id'), 'purpose', ['hierarchy_id'], unique=False)
    op.create_index(op.f('ix_purpose_service_type_id'), 'purpose', ['service_type_id'], unique=False)
    op.create_index(op.f('ix_purpose_status'), 'purpose', ['status'], unique=False)
    op.create_index(op.f('ix_purpose_supplier_id'), 'purpose', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purpose_supplier_id'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_status'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_service_type_id'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_hierarchy_id'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_description'), table_name='purpose')
    op.drop_index(op.f('ix_purpose_content'), table_name='purpose')
    op.drop_index(op.f('ix_hierarchy_path'), table_name='hierarchy')
    # ### end Alembic commands ###
