"""add service type table

Revision ID: 2025-01-15-add-service-type
Revises: cb904bc8ba3e
Create Date: 2025-01-15 12:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2025-01-15-add-service-type"
down_revision: Union[str, Sequence[str], None] = "cb904bc8ba3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_type_id"), "service_type", ["id"], unique=False)
    op.create_index(op.f("ix_service_type_name"), "service_type", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_service_type_name"), table_name="service_type")
    op.drop_index(op.f("ix_service_type_id"), table_name="service_type")
    op.drop_table("service_type")
    # ### end Alembic commands ### 