"""file attachments

Revision ID: 66c7bbe2cbe5
Revises: 297142562641
Create Date: 2025-06-21 19:33:49.223162

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66c7bbe2cbe5"
down_revision: Union[str, Sequence[str], None] = "297142562641"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("s3_key", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("purpose_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["purpose_id"],
            ["purpose.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
    )
    op.create_index(
        op.f("ix_file_attachment_id"), "file_attachment", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_file_attachment_purpose_id"),
        "file_attachment",
        ["purpose_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_attachment_purpose_id"), table_name="file_attachment")
    op.drop_index(op.f("ix_file_attachment_id"), table_name="file_attachment")
    op.drop_table("file_attachment")
    # ### end Alembic commands ###
