"""add_file_icon_id_to_supplier

Revision ID: 32f9ee461e64
Revises: 6eee6789fa73
Create Date: 2025-06-26 09:17:12.593614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32f9ee461e64'
down_revision: Union[str, Sequence[str], None] = '6eee6789fa73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('file_icon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'supplier', 'file_attachment', ['file_icon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_column('supplier', 'file_icon_id')
    # ### end Alembic commands ###
