apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculaud-be.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calculaud-be.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "calculaud-be.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "calculaud-be.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calculaud-be.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.postgresql.enabled }}
      initContainers:
      - name: wait-for-db
        image: postgres:15-alpine
        command:
        - sh
        - -c
        - |
          until pg_isready -h {{ include "calculaud-be.postgresql.host" . }} -p {{ include "calculaud-be.postgresql.port" . }} -U {{ include "calculaud-be.postgresql.username" . }}; do
            echo "Waiting for database..."
            sleep 2
          done
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: DATABASE_PASSWORD
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: {{ include "calculaud-be.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        # Database URL (constructed from components)
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: DATABASE_PASSWORD
        - name: DATABASE_URL
          value: {{ include "calculaud-be.databaseUrl" . | quote }}
        # Environment variables from ConfigMap
        {{- range $key, $value := .Values.config }}
        {{- if $value }}
        - name: {{ $key | upper | replace "." "_" }}
          valueFrom:
            configMapKeyRef:
              name: {{ include "calculaud-be.fullname" $ }}-config
              key: {{ $key | upper | replace "." "_" }}
        {{- end }}
        {{- end }}
        # S3 configuration from ConfigMap
        - name: S3_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: {{ include "calculaud-be.fullname" . }}-config
              key: S3_USE_SSL
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ include "calculaud-be.fullname" . }}-config
              key: S3_BUCKET_NAME
        - name: S3_KEY_PREFIX
          valueFrom:
            configMapKeyRef:
              name: {{ include "calculaud-be.fullname" . }}-config
              key: S3_KEY_PREFIX
        {{- if .Values.s3.storageClass }}
        - name: S3_STORAGE_CLASS
          valueFrom:
            configMapKeyRef:
              name: {{ include "calculaud-be.fullname" . }}-config
              key: S3_STORAGE_CLASS
        {{- end }}
        # Auth configuration from ConfigMap
        - name: OAUTH_SCOPES
          valueFrom:
            configMapKeyRef:
              name: {{ include "calculaud-be.fullname" . }}-config
              key: OAUTH_SCOPES
        - name: AUTH_ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: {{ include "calculaud-be.fullname" . }}-config
              key: AUTH_ALGORITHM
        # Sensitive environment variables from Secret
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: AWS_SECRET_ACCESS_KEY
        {{- if .Values.s3.region }}
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: AWS_REGION
        {{- end }}
        {{- if .Values.s3.endpointUrl }}
        - name: S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: S3_ENDPOINT_URL
        {{- end }}
        - name: S3_BUCKET_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: S3_BUCKET_URL
        - name: AUTH_JWKS_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: AUTH_JWKS_URL
        - name: AUTH_ISSUER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: AUTH_ISSUER
        {{- if .Values.auth.audience }}
        - name: AUTH_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: AUTH_AUDIENCE
        {{- end }}
        - name: AUTH_TOKEN_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: AUTH_TOKEN_ENDPOINT_URL
        - name: AUTH_OIDC_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: AUTH_OIDC_URL
        {{- if .Values.auth.oauth.clientId }}
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.existingSecret | default (printf "%s-secret" (include "calculaud-be.fullname" .)) }}
              key: OAUTH_CLIENT_ID
        {{- end }}
        {{- with .Values.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.healthcheck.liveness.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthcheck.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.liveness.timeoutSeconds }}
          successThreshold: {{ .Values.healthcheck.liveness.successThreshold }}
          failureThreshold: {{ .Values.healthcheck.liveness.failureThreshold }}
        readinessProbe:
          httpGet:
            path: {{ .Values.healthcheck.readiness.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthcheck.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.readiness.timeoutSeconds }}
          successThreshold: {{ .Values.healthcheck.readiness.successThreshold }}
          failureThreshold: {{ .Values.healthcheck.readiness.failureThreshold }}
        startupProbe:
          httpGet:
            path: {{ .Values.healthcheck.startup.path }}
            port: http
          initialDelaySeconds: {{ .Values.healthcheck.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.startup.timeoutSeconds }}
          successThreshold: {{ .Values.healthcheck.startup.successThreshold }}
          failureThreshold: {{ .Values.healthcheck.startup.failureThreshold }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.cache
        {{- with .Values.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}