{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calculaud-be.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calculaud-be.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculaud-be.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calculaud-be.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql-service
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: {{ .Values.postgresql.port }}
    targetPort: postgresql
    protocol: TCP
  selector:
    {{- include "calculaud-be.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "calculaud-be.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calculaud-be.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "calculaud-be.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      {{- include "calculaud-be.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "calculaud-be.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: postgresql
        image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        ports:
        - name: postgresql
          containerPort: {{ .Values.postgresql.port }}
          protocol: TCP
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "calculaud-be.fullname" . }}-postgresql
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "calculaud-be.fullname" . }}-postgresql
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ include "calculaud-be.fullname" . }}-postgresql
              key: POSTGRES_DB
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 12 }}
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - $(POSTGRES_USER)
            - -d
            - $(POSTGRES_DB)
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 999
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
      labels:
        {{- include "calculaud-be.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql-storage
    spec:
      accessModes: {{ .Values.postgresql.persistence.accessModes }}
      {{- if .Values.postgresql.persistence.storageClass }}
      {{- if (eq "-" .Values.postgresql.persistence.storageClass) }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.postgresql.persistence.size | quote }}
{{- end }}