# Development environment values for calculaud-be
# Override default values for development environment

# Single replica for development
replicaCount: 1

# Development image configuration
image:
  tag: "dev-latest"
  pullPolicy: Always

# Development configuration
config:
  debug: true
  environment: "development"

# Use external PostgreSQL for development (consistent with production)
postgresql:
  enabled: false  # Always use external PostgreSQL
  external:
    host: "postgres-dev.yourdomain.local"
    port: 5432
    username: "calculaud"
    password: "dev-password-123"
    database: "calculaud_dev"

# Development S3 configuration (external S3-compatible storage)
s3:
  accessKeyId: "dev-access-key"
  secretAccessKey: "dev-secret-key"
  region: "us-east-1"
  endpointUrl: "https://s3-dev.yourdomain.local"
  bucketName: "calculaud-dev"
  bucketUrl: "https://s3-dev.yourdomain.local/calculaud-dev"
  useSsl: true

# Development authentication (using mock auth or dev auth server)
auth:
  jwksUrl: "https://dev-auth.example.com/.well-known/jwks.json"
  issuer: "https://dev-auth.example.com/"
  audience: "calculaud-dev-api"
  tokenEndpointUrl: "https://dev-auth.example.com/oauth/token"
  oidcUrl: "https://dev-auth.example.com/"
  oauth:
    clientId: "calculaud-dev-client"

# Development ingress
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # No SSL for dev
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
  hosts:
    - host: calculaud-dev.local
      paths:
        - path: /
          pathType: Prefix
  tls: []  # No TLS for development

# Lower resource requirements for development
resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Disable autoscaling in development
autoscaling:
  enabled: false

# More relaxed health checks for development
healthcheck:
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 30
    failureThreshold: 5
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 5
  startup:
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 60

# Development-specific environment variables
extraEnvVars:
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: RELOAD
    value: "true"