# Deployment for Calculaud Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculaud-be
  namespace: calculaud
  labels:
    app.kubernetes.io/name: calculaud-be
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: calculaud-be
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: calculaud-be
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: "1.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: calculaud-be
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: calculaud-be
        image: calculaud/calculaud-be:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        # Environment variables from ConfigMap
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: APP_NAME
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: DEBUG
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: VERSION
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: ENVIRONMENT
        - name: API_V1_PREFIX
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: API_V1_PREFIX
        - name: DEFAULT_PAGE_SIZE
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: DEFAULT_PAGE_SIZE
        - name: MAX_PAGE_SIZE
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: MAX_PAGE_SIZE
        - name: USD_TO_ILS_RATE
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: USD_TO_ILS_RATE
        - name: MAX_FILE_SIZE_MB
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: MAX_FILE_SIZE_MB
        - name: S3_USE_SSL
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: S3_USE_SSL
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: S3_BUCKET_NAME
        - name: S3_KEY_PREFIX
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: S3_KEY_PREFIX
        - name: OAUTH_SCOPES
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: OAUTH_SCOPES
        - name: AUTH_ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: calculaud-be-config
              key: AUTH_ALGORITHM
        # Environment variables from Secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: DATABASE_URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: AWS_REGION
        - name: S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: S3_ENDPOINT_URL
        - name: S3_BUCKET_URL
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: S3_BUCKET_URL
        - name: AUTH_JWKS_URL
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: AUTH_JWKS_URL
        - name: AUTH_ISSUER
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: AUTH_ISSUER
        - name: AUTH_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: AUTH_AUDIENCE
        - name: AUTH_TOKEN_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: AUTH_TOKEN_ENDPOINT_URL
        - name: AUTH_OIDC_URL
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: AUTH_OIDC_URL
        - name: OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: calculaud-be-secret
              key: OAUTH_CLIENT_ID
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/startup
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /app/.cache
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
# ServiceAccount for the application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: calculaud-be
  namespace: calculaud
  labels:
    app.kubernetes.io/name: calculaud-be
    app.kubernetes.io/component: serviceaccount